---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: debian-7.4

suites:
  - name: xenforodb
    run_list:
      - recipe[up2date]
      - role[xenforodb]
    driver_config:
      network:
      - ["private_network", {ip: "192.168.234.12"}]
      customize:
        memory: 1024
    attributes:
      mysql:
        bind_address: "192.168.234.12"
      bp-percona:
        bind-address: "192.168.234.12"
      tags: 
      - "id-vagrant"
  - name: xenforomem
    run_list:
      - recipe[up2date]
      - role[xenforomem]
    driver_config:
      network:
      - ["private_network", {ip: "192.168.234.13"}]
    attributes:
      tags: 
      - "id-vagrant"
  - name: xenforo1
    run_list:
      - recipe[up2date]
      - role[xenforo]
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8081, auto_correct: true}]
      - ["private_network", {ip: "192.168.234.10"}]
    attributes:
      xenforo:
        install_allow_from: ""
        customlog: "/var/log/apache2/xenforo-access.log combined"
        errorlog: "/var/log/apache2/xenforo-error.log"
      tags: 
      - "id-vagrant"
  - name: xenforo2
    run_list:
      - recipe[up2date]
      - role[xenforo]
    driver_config:
      network:
      - ["forwarded_port", {guest: 443, host: 8444, auto_correct: true}]
      - ["private_network", {ip: "192.168.234.11"}]
    attributes:
      xenforo:
        enable_ssl: true
        install_allow_from: ""
        customlog: "/var/log/apache2/xenforo-access.log combined"
        errorlog: "/var/log/apache2/xenforo-error.log"
      tags: 
      - "id-vagrant"

